set(PICO_PORT_FILES 
                    ${CMAKE_CURRENT_LIST_DIR}/pico_port/micro_time.cpp
                    ${CMAKE_CURRENT_LIST_DIR}/pico_port/system_setup.cpp
)

set(CMSIS_SOURCE_FILES 
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Include/Internal/arm_nn_compiler.h
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Include/arm_nn_math_types.h
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Include/arm_nn_tables.h
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Include/arm_nn_types.h
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Include/arm_nnfunctions.h
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Include/arm_nnsupportfunctions.h
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ActivationFunctions/arm_nn_activation_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ActivationFunctions/arm_relu6_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ActivationFunctions/arm_relu_q15.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ActivationFunctions/arm_relu_q7.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_add_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c
                    # ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_mul_acpp_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_mul_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_mul_s16_batch_offset.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_mul_s16_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_maximum_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/BasicMathFunctions/arm_minimum_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConcatenationFunctions/arm_concatenation_s8_w.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConcatenationFunctions/arm_concatenation_s8_x.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConcatenationFunctions/arm_concatenation_s8_y.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConcatenationFunctions/arm_concatenation_s8_z.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_1x1_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_1x1_s4_fast.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_even_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_get_buffer_sizes_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_get_buffer_sizes_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_get_buffer_sizes_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_fast_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_get_buffer_sizes_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_get_buffer_sizes_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_get_buffer_sizes_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_s4_opt.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_row_offset_s8_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s4_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_transpose_conv_get_buffer_sizes_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_transpose_conv_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ConvolutionFunctions/arm_transpose_conv_wrapper_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_batch_matmul_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_batch_matmul_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_get_buffer_sizes_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_get_buffer_sizes_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_per_channel_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_fully_connected_wrapper_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_vector_sum_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/FullyConnectedFunctions/arm_vector_sum_s8_s64.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/LSTMFunctions/arm_lstm_unidirectional_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/LSTMFunctions/arm_lstm_unidirectional_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_lstm_calculate_gate_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_lstm_calculate_gate_s8_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_lstm_step_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_lstm_step_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_interleaved_t_even_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8_s32.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_transpose_conv_row_s8_s32.c
                    # ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mul_result_acpp_s16.c
                    # ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mul_result_acpp_s8_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_per_ch_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s16_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s4.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_nntables.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/NNSupportFunctions/arm_s8_to_s16_unordered_with_offset.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PadFunctions/arm_pad_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PoolingFunctions/arm_avgpool_get_buffer_sizes_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PoolingFunctions/arm_avgpool_get_buffer_sizes_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PoolingFunctions/arm_avgpool_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PoolingFunctions/arm_avgpool_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PoolingFunctions/arm_max_pool_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/PoolingFunctions/arm_max_pool_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/ReshapeFunctions/arm_reshape_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SVDFunctions/arm_svdf_get_buffer_sizes_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SVDFunctions/arm_svdf_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SVDFunctions/arm_svdf_state_s16_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SoftmaxFunctions/arm_nn_softmax_common_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SoftmaxFunctions/arm_softmax_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SoftmaxFunctions/arm_softmax_s8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SoftmaxFunctions/arm_softmax_s8_s16.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/SoftmaxFunctions/arm_softmax_u8.c
                    ${CMAKE_CURRENT_LIST_DIR}/third_party/CMSIS-NN/Source/TransposeFunctions/arm_transpose_s8.c
                )

set(TENSORFLOW_CMSIS_SOURCE_FILES 
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/add.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/batch_matmul.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/conv.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/depthwise_conv.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/mul.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/pooling.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/softmax.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/svdf.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/transpose_conv.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cmsis_nn/unidirectional_sequence_lstm.cc
)

set(TFLITE_MICRO_SOURCE_FILES
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/core/api/error_reporter.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/core/api/error_reporter.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/core/c/builtin_op_data.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/core/c/tflite_types.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/kernels/internal/compatibility_macros.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/schema/schema_generated.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/schema/schema_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/compiler/mlir/lite/schema/schema_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/builtin_op_data.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/builtin_ops.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/c/builtin_op_data.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/c/c_api_types.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/c/common.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/context_util.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/api/error_reporter.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/api/flatbuffer_conversions.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/api/flatbuffer_conversions.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/api/tensor_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/api/tensor_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/c/builtin_op_data.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/c/c_api_types.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/c/common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/c/common.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/core/macros.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/common.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/compatibility.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/cppmath.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/max.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/min.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/optimized/neon_check.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/portable_tensor.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/portable_tensor_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/portable_tensor_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/quantization_util.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/quantization_util.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/add.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/add_n.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/arg_min_max.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/batch_matmul.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/batch_to_space_nd.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/binary_function.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/broadcast_args.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/broadcast_to.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/ceil.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/comparisons.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/comparisons.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/concatenation.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/cumsum.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/depth_to_space.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/depthwiseconv_float.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/depthwiseconv_uint8.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/dequantize.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/div.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/elu.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/exp.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/fill.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/floor.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/floor_div.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/floor_mod.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/fully_connected.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/hard_swish.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/add.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/depthwise_conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/fully_connected.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/l2normalization.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/logistic.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/mean.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/mul.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/pooling.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/tanh.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops/transpose_conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/l2normalization.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/leaky_relu.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/log_softmax.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/logistic.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/lstm_cell.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/maximum_minimum.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/mul.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/neg.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/pad.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/pooling.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/portable_tensor_utils_impl.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/prelu.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/process_broadcast_shapes.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/quantize.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/reduce.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/requantize.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/resize_bilinear.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/resize_nearest_neighbor.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/round.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/select.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/slice.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/softmax.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/space_to_batch_nd.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/space_to_depth.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/strided_slice.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/sub.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/tanh.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/transpose.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/reference/transpose_conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/runtime_shape.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/runtime_shape.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/strided_slice_logic.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/tensor_ctypes.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/tensor_ctypes.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/tensor_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/internal/types.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/kernel_util.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/kernel_util.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/op_macros.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/kernels/padding.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/ibuffer_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/non_persistent_arena_buffer_allocator.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/non_persistent_arena_buffer_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/persistent_arena_buffer_allocator.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/persistent_arena_buffer_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/recording_single_arena_buffer_allocator.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/recording_single_arena_buffer_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/single_arena_buffer_allocator.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/arena_allocator/single_arena_buffer_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/benchmarks/micro_benchmark.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/compatibility.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/compression.h
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/debug_log.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/debug_log.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/fake_micro_context.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/fake_micro_context.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/flatbuffer_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/flatbuffer_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/hexdump.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/hexdump.h
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/hexdump_test.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/activation_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/activations.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/activations.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/activations_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/add.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/add_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/add_n.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/arg_min_max.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/assign_variable.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/batch_matmul.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/batch_to_space_nd.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/broadcast_args.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/broadcast_to.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/call_once.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cast.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/ceil.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/circular_buffer.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/circular_buffer.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/circular_buffer_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.h

                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/comparisons.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/concatenation.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/conv_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/conv_test.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/cumsum.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/decompress.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/decompress.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/decompress_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/depth_to_space.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/depthwise_conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/depthwise_conv_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/dequantize.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/dequantize.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/dequantize_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/detection_postprocess.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/div.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/elementwise.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/elu.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/embedding_lookup.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/ethosu.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/ethosu.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/exp.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/expand_dims.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/fill.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/floor.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/floor_div.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/floor_mod.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/fully_connected.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/fully_connected_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/gather.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/gather_nd.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/hard_swish.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/hard_swish.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/hard_swish_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/if.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/kernel_runner.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/kernel_runner.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/kernel_util.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/kernel_util.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/l2_pool_2d.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/l2norm.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/leaky_relu.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/leaky_relu.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/leaky_relu_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/log_softmax.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/logical.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/logical.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/logical_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/logistic.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/logistic.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/logistic_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/lstm_eval.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/lstm_eval.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/lstm_eval_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/lstm_eval_test.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/lstm_shared.h
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/maximum_minimum.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/micro_ops.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/micro_tensor_utils.cc
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflopadw/lite/micro/kernels/micro_tensor_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/mirror_pad.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/mul.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/mul_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/neg.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/pack.cc
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/pad.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/pad.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/pooling.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/pooling_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/prelu.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/prelu.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/prelu_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/quantize.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/quantize.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/quantize_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/read_variable.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/reduce.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/reduce.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/reduce_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/reshape.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/reshape.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/reshape_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/resize_bilinear.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/round.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/select.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/shape.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/slice.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/softmax.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/softmax_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/space_to_batch_nd.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/space_to_depth.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/split.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/split_v.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/squared_difference.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/squeeze.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/strided_slice.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/strided_slice.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/strided_slice_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/sub.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/sub.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/sub_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/svdf.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/svdf_common.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/tanh.cc
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/transpose.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/transpose_conv.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/unpack.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/var_handle.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/while.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/kernels/zeros_like.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_helpers.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_helpers.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/greedy_memory_planner.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/linear_memory_planner.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/linear_memory_planner.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/memory_plan_struct.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/micro_memory_planner.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/non_persistent_buffer_planner_shim.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/memory_planner/non_persistent_buffer_planner_shim.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_allocation_info.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_allocation_info.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_allocator.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_arena_constants.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_common.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_context.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_context.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_graph.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_interpreter.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_interpreter.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_interpreter_context.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_interpreter_context.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_interpreter_graph.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_interpreter_graph.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_log.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_log.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_mutable_op_resolver.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_op_resolver.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_op_resolver.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_profiler.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_profiler.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_profiler_interface.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_resource_variable.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_resource_variable.h
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_time.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_time.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_utils.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/micro_utils.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/mock_micro_graph.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/mock_micro_graph.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/recording_micro_allocator.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/recording_micro_allocator.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/recording_micro_interpreter.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/span.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/static_vector.h
                        # ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/system_setup.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/system_setup.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/test_helper_custom_ops.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/test_helper_custom_ops.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/test_helpers.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/test_helpers.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/testing/micro_test.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/tflite_bridge/flatbuffer_conversions_bridge.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/tflite_bridge/flatbuffer_conversions_bridge.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/tflite_bridge/micro_error_reporter.cc
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/micro/tflite_bridge/micro_error_reporter.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/portable_type_to_tflitetype.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/schema/schema_generated.h
                        ${CMAKE_CURRENT_LIST_DIR}/tensorflow/lite/schema/schema_utils.h
)